export const categories = {
  children: {
    children05: "Малюкам 0-5 років",
    children69: "Дітям 6-9 років",
    children1014: "Молодшим підліткам 10-14 років",
    teens1416: "Підліткам 14-16 років",
    encyclopedy: "Енциклопеції",
    childrenPsychology: "Дорослішання та статеве виховання. Дитяча психологія",
    abc: "Букварі й абетки",
    comics: "Комікси",
    wimelbuchs: "Вімельбухи",
    poems: "Вірші",
    religion: "Релігія для дітей",
    logoped: "Логопедична серія",
    polish: "Польська мова",
    english: "Англійська мова",
    other: "Інше",
  },
  adult: {
    forParents: "Книги для батьків (виховання, вагітність)",
    business: "Бізнес, кар'єра, фінанси",
    motivation: "Саморозвиток, мотивація",
    women: "Жіноче: душа, розум, тіло",
    relationships: "Стосунки, любов, шлюб",
    otherNF: "Різне (нехудожнє)",
    poetry: "Поезія",
    youngAdult: "Young Adult, молоді дорослі (книги 14-16+)",
    novelsUA: "Сучасна проза (українські автори)",
    novels: "Сучасна проза (закордонні автори)",
    classics: "Українська і світова класична література",
    loveNovels: "Любовні романи",
    historicalNovels: "Історичні романи",
    thrillers: "Триллери",
    detectives: "Детективи",
    fantasy: "Фентезі",
    scifi: "Фантасика",
    otherF: "Різне (художнє)",
  },
};
